"""add comment image relation

Revision ID: 0705760b5f99
Revises: 54a35edc2381
Create Date: 2022-03-15 13:04:56.191933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0705760b5f99'
down_revision = '54a35edc2381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_comment_images', sa.Column('commentsId', sa.Integer(), nullable=False))
    op.drop_constraint('community_comment_images_commentId_fkey', 'community_comment_images', type_='foreignkey')
    op.create_foreign_key(None, 'community_comment_images', 'community_comments', ['commentsId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('community_comment_images', 'commentId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_comment_images', sa.Column('commentId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'community_comment_images', type_='foreignkey')
    op.create_foreign_key('community_comment_images_commentId_fkey', 'community_comment_images', 'community_comments', ['commentId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('community_comment_images', 'commentsId')
    # ### end Alembic commands ###
