"""add new relations community post,community post image,comments

Revision ID: 1fb5708629c2
Revises: 396aa59a4970
Create Date: 2022-03-10 13:03:31.130383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fb5708629c2'
down_revision = '396aa59a4970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_CommunityPosts_id', table_name='CommunityPosts')
    op.drop_table('CommunityPosts')
    op.drop_index('ix_Users_id', table_name='Users')
    op.drop_table('Users')
    op.add_column('community_posts', sa.Column('post_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('community_posts', 'post_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_posts', sa.Column('post_data', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('community_posts', 'post_date')
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=155), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=155), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=155), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=155), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=155), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('profile_picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Users_pkey'),
    sa.UniqueConstraint('email', name='Users_email_key'),
    sa.UniqueConstraint('username', name='Users_username_key')
    )
    op.create_index('ix_Users_id', 'Users', ['id'], unique=False)
    op.create_table('CommunityPosts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"CommunityPosts_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('post_title', sa.VARCHAR(length=155), autoincrement=False, nullable=False),
    sa.Column('post_data', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='CommunityPosts_pkey')
    )
    op.create_index('ix_CommunityPosts_id', 'CommunityPosts', ['id'], unique=False)
    # ### end Alembic commands ###
