"""added user and admin tables

Revision ID: 4e23305fa470
Revises: d481bf518e19
Create Date: 2022-03-06 13:43:49.917173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e23305fa470'
down_revision = 'd481bf518e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=155), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Admins_id'), 'Admins', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=155), nullable=False),
    sa.Column('last_name', sa.String(length=155), nullable=False),
    sa.Column('username', sa.String(length=155), nullable=False),
    sa.Column('email', sa.String(length=155), nullable=False),
    sa.Column('phone_number', sa.String(length=35), nullable=False),
    sa.Column('location', sa.String(length=155), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Admins_id'), table_name='Admins')
    op.drop_table('Admins')
    # ### end Alembic commands ###
