"""add new relations vote for post and vote for comment

Revision ID: 54a35edc2381
Revises: 1fb5708629c2
Create Date: 2022-03-10 13:53:54.445072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a35edc2381'
down_revision = '1fb5708629c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_up_vote_post_id', table_name='up_vote_post')
    op.drop_table('up_vote_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('up_vote_post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='up_vote_post_pkey')
    )
    op.create_index('ix_up_vote_post_id', 'up_vote_post', ['id'], unique=False)
    # ### end Alembic commands ###
