"""add new model call disease_image and  added relatinoship between disease and image

Revision ID: 7c9c837c3349
Revises: f0ab7459287b
Create Date: 2022-02-22 04:31:02.811215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9c837c3349'
down_revision = 'f0ab7459287b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_disease_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.Text(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['plant_deseases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_disease_images_id'), 'plant_disease_images', ['id'], unique=False)
    op.add_column('plant_desease_medicines', sa.Column('disease_id', sa.Integer(), nullable=True))
    op.drop_constraint('plant_desease_medicines_plant_id_fkey', 'plant_desease_medicines', type_='foreignkey')
    op.create_foreign_key(None, 'plant_desease_medicines', 'plant_deseases', ['disease_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('plant_desease_medicines', 'plant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_desease_medicines', sa.Column('plant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'plant_desease_medicines', type_='foreignkey')
    op.create_foreign_key('plant_desease_medicines_plant_id_fkey', 'plant_desease_medicines', 'plant_deseases', ['plant_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('plant_desease_medicines', 'disease_id')
    op.drop_index(op.f('ix_plant_disease_images_id'), table_name='plant_disease_images')
    op.drop_table('plant_disease_images')
    # ### end Alembic commands ###
