"""Drop nullable short description

Revision ID: bdd81ff9668a
Revises: 1af6c279ea8e
Create Date: 2022-02-22 02:13:48.081633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd81ff9668a'
down_revision = '1af6c279ea8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_deseases', 'desease_short_description',
               existing_type=sa.VARCHAR(length=155),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_deseases', 'desease_short_description',
               existing_type=sa.VARCHAR(length=155),
               nullable=False)
    # ### end Alembic commands ###
