"""drop null value in description in medicine table

Revision ID: d481bf518e19
Revises: 7c9c837c3349
Create Date: 2022-02-28 02:09:24.031481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd481bf518e19'
down_revision = '7c9c837c3349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_desease_medicines', 'medicene_description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_desease_medicines', 'medicene_description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
