"""changed relationship between decese and medicene models

Revision ID: f0ab7459287b
Revises: 825381388566
Create Date: 2022-02-22 03:50:30.858325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ab7459287b'
down_revision = '825381388566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plant_desease_medicines_plant_id_fkey', 'plant_desease_medicines', type_='foreignkey')
    op.create_foreign_key(None, 'plant_desease_medicines', 'plant_deseases', ['plant_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant_desease_medicines', type_='foreignkey')
    op.create_foreign_key('plant_desease_medicines_plant_id_fkey', 'plant_desease_medicines', 'plants', ['plant_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
