"""add nullable true to user location

Revision ID: fcfdf84c2b59
Revises: 0705760b5f99
Create Date: 2022-04-13 03:46:03.257792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfdf84c2b59'
down_revision = '0705760b5f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(length=155),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(length=155),
               nullable=False)
    # ### end Alembic commands ###
